# Generated by Django 2.2.28 on 2023-03-21 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('TrackID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('SpotifyID', models.CharField(max_length=300)),
                ('TrackName', models.CharField(max_length=200)),
                ('album', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('likes', models.IntegerField(blank=True, default=0)),
                ('dislikes', models.IntegerField(blank=True, default=0)),
                ('listens', models.IntegerField(blank=True, default=0)),
                ('cover_imageURL', models.URLField(blank=True)),
                ('trackURL', models.URLField(blank=True)),
                ('previewURL', models.URLField(blank=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Tracks',
            },
        ),
        migrations.CreateModel(
            name='UserClass',
            fields=[
                ('UserID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('userDisLikes', models.ManyToManyField(related_name='user_dislikes', to='spotiview.Track')),
                ('userLikes', models.ManyToManyField(related_name='user_likes', to='spotiview.Track')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('CommentID', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('comment', models.TextField(max_length=200)),
                ('DateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('TrackID', models.ForeignKey(auto_created=True, on_delete=django.db.models.deletion.CASCADE, to='spotiview.Track')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotiview.UserClass')),
            ],
            options={
                'verbose_name_plural': 'comments',
            },
        ),
    ]
