# Generated by Django 2.2.28 on 2023-03-02 03:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('TrackID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('SpotifyID', models.CharField(max_length=300, unique=True)),
                ('TrackName', models.CharField(max_length=200)),
                ('album', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('listens', models.IntegerField(default=0)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name_plural': 'Tracks',
            },
        ),
        migrations.CreateModel(
            name='UserClass',
            fields=[
                ('UserID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('CommentID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('comment', models.CharField(max_length=200)),
                ('DateTime', models.DateTimeField()),
                ('TrackID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotiview.Track')),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotiview.UserClass')),
            ],
            options={
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
