# Generated by Django 2.2.28 on 2023-03-05 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotiview', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='SpotifyID',
            field=models.CharField(blank=True, max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='TrackID',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='TrackName',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='track',
            name='artist',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='track',
            name='dislikes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='track',
            name='likes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='track',
            name='listens',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
