# Generated by Django 2.2.28 on 2023-03-20 07:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spotiview', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('date',), 'verbose_name_plural': 'Comments'},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='DateTime',
        ),
        migrations.AddField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='track',
            name='cover_imageURL',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='track',
            name='previewURL',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='track',
            name='trackURL',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='userclass',
            name='userDisLikes',
            field=models.ManyToManyField(related_name='user_dislikes', to='spotiview.Track'),
        ),
        migrations.AddField(
            model_name='userclass',
            name='userLikes',
            field=models.ManyToManyField(related_name='user_likes', to='spotiview.Track'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='track',
            name='SpotifyID',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='track',
            name='dislikes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='track',
            name='likes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='track',
            name='listens',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='track',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
