# Generated by Django 2.2.28 on 2023-03-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotiview', '0002_auto_20230320_0751'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': 'comments'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
