# Generated by Django 2.2.28 on 2023-03-20 08:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spotiview', '0004_auto_20230320_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
        ),
    ]
