# Generated by Django 2.2.28 on 2023-03-07 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotiview', '0005_auto_20230305_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='TrackID',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
