# Generated by Django 2.2.28 on 2023-03-20 08:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spotiview', '0005_comment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='date',
        ),
        migrations.AddField(
            model_name='comment',
            name='DateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
