# Generated by Django 2.2.28 on 2023-03-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotiview', '0006_auto_20230307_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='SpotifyID',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='track',
            name='TrackName',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='track',
            name='artist',
            field=models.CharField(max_length=200),
        ),
    ]
