# Generated by Django 2.2.28 on 2023-03-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotiview', '0006_auto_20230320_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
    ]
