# Generated by Django 2.2.28 on 2023-03-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotiview', '0007_auto_20230307_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='track_images'),
        ),
    ]
