# Generated by Django 2.2.28 on 2023-03-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotiview', '0008_track_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
