# Generated by Django 2.2.28 on 2023-03-16 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotiview', '0010_auto_20230312_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='userDisLikes',
            field=models.ManyToManyField(related_name='user_dislikes', to='spotiview.UserClass'),
        ),
        migrations.AddField(
            model_name='track',
            name='userLikes',
            field=models.ManyToManyField(related_name='user_likes', to='spotiview.UserClass'),
        ),
    ]
