# Generated by Django 2.2.28 on 2023-03-16 18:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spotiview', '0012_auto_20230316_0105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='userDisLikes',
        ),
        migrations.RemoveField(
            model_name='track',
            name='userLikes',
        ),
        migrations.AddField(
            model_name='userclass',
            name='userDisLikes',
            field=models.ManyToManyField(related_name='user_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userclass',
            name='userLikes',
            field=models.ManyToManyField(related_name='user_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
