# Generated by Django 2.2.28 on 2023-03-16 19:15

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spotiview', '0013_auto_20230316_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userclass',
            name='userDisLikes',
        ),
        migrations.AddField(
            model_name='userclass',
            name='userDisLikes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=django.utils.timezone.now, size=None),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='userclass',
            name='userLikes',
        ),
        migrations.AddField(
            model_name='userclass',
            name='userLikes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=django.utils.timezone.now, size=None),
            preserve_default=False,
        ),
    ]
