# Generated by Django 2.2.28 on 2023-03-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotiview', '0015_auto_20230316_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='userclass',
            name='userDisLikes',
            field=models.ManyToManyField(related_name='user_dislikes', to='spotiview.Track'),
        ),
        migrations.AddField(
            model_name='userclass',
            name='userLikes',
            field=models.ManyToManyField(related_name='user_likes', to='spotiview.Track'),
        ),
    ]
