# Generated by Django 2.2.28 on 2023-03-16 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotiview', '0016_auto_20230316_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='userDisLikes',
        ),
        migrations.RemoveField(
            model_name='track',
            name='userLikes',
        ),
    ]
