# Generated by Django 2.2.28 on 2023-03-20 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotiview', '0020_auto_20230319_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='spotiview.Track'),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
